apiVersion: v1
kind: Secret
metadata:
  name: cdscdscvfvfv12345-secret
  namespace: cdscdscvfvfv12345
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
